FROM node:6

# this pattern allows docker to cache npm dependencies based on changes to the package.json file
ADD package.json /tmp/package.json
RUN cd /tmp && npm install
RUN mkdir -p /usr/src/status.adobe.com && cp -a /tmp/node_modules /usr/src/status.adobe.com

WORKDIR /usr/src/status.adobe.com

ADD . /usr/src/status.adobe.com

RUN npm run build